# Generated by Django 6.0 on 2025-12-03 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submitted_answers',
            field=models.JSONField(blank=True, default=list, help_text='Raw submitted answers from client (used for auditing / replay)', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='answers',
            field=models.JSONField(blank=True, default=list, help_text='Graded answers/results saved by server', null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0, help_text='Score as percent (0-100)'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total_time',
            field=models.IntegerField(default=0, help_text='Total time in seconds'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text='List of question objects (type, text, acceptable_answers, table_entries, etc.)', null=True),
        ),
    ]
